substitutions:
  device_name: "medisana-bs444"

external_components:
  - source:
      type: git
      url: https://github.com/bwynants/weegschaal
      ref: main
    components: [ medisana_bs444 ]

esphome:
  name: ${device_name}
  friendly_name: Medisana BS444
  project:
    name: bwynants.$device_name
    version: "0.20"
  areas:
    - id: bathroom_area
      name: "Bathroom"
  devices:
    - id: scale_user_1
      name: "Scale User 1"
      area_id: bathroom_area
    - id: scale_user_2
      name: "Scale User 2"
      area_id: bathroom_area

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:
  level: INFO

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption

ota:
  platform: esphome
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${device_name} Fallback Hotspot
    ap_timeout: 15s

captive_portal:
    
web_server:
  port: 80

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: false

ble_client:
  - mac_address: !secret medisana_scale
    id: medisababs44_ble_id

medisana_bs444:
  - id: myscale
    ble_client_id: medisababs44_ble_id
    timeoffset: true

binary_sensor:
  - platform: medisana_bs444
    medisana_bs444_id: myscale
    #brigitte
    male_1:
      device_id: scale_user_1
      name: "Male user 1"
    female_1:
      device_id: scale_user_1
      name: "Female user 1"
    highactivity_1:
      device_id: scale_user_1
      name: "High Activity user 1"
    # bert
    male_2:
      device_id: scale_user_2
      name: "Male user 2"
    female_2:
      device_id: scale_user_2
      name: "Female user 2"
    highactivity_2:
      device_id: scale_user_2
      name: "High Activity user 2"

sensor:
  - platform: medisana_bs444
    medisana_bs444_id: myscale
    weight_1:
      device_id: scale_user_1
      name: "Weight user 1"
    kcal_1:
      device_id: scale_user_1
      name: "kcal user 1"
    fat_1:
      device_id: scale_user_1
      name: "Fat user 1"
    tbw_1:
      device_id: scale_user_1
      name: "Water user 1"
    muscle_1:
      device_id: scale_user_1
      name: "Muscle user 1"
    bone_1:
      device_id: scale_user_1
      name: "Bone user 1"
    bmi_1:
      device_id: scale_user_1
      name: "BMI user 1"
    age_1:
      device_id: scale_user_1
      name: "Age user 1"
    size_1:
      device_id: scale_user_1
      name: "Size user 1"

    weight_2:
      device_id: scale_user_2
      name: "Weight user 2"
    kcal_2:
      device_id: scale_user_2
      name: "kcal user 2"
    fat_2:
      device_id: scale_user_2
      name: "Fat user 2"
    tbw_2:
      device_id: scale_user_2
      name: "Water user 2"
    muscle_2:
      device_id: scale_user_2
      name: "Muscle user 2"
    bone_2:
      device_id: scale_user_2
      name: "Bone user 2"
    bmi_2:
      device_id: scale_user_2
      name: "BMI user 2"
    age_2:
      device_id: scale_user_2
      name: "Age user 2"
    size_2:
      device_id: scale_user_2
      name: "Size user 2"

  - platform: wifi_signal
    name: Wi-Fi Signal
    update_interval: 60s
    entity_category: diagnostic


button:
  # A reboot button is always useful
  - platform: restart
    entity_category: diagnostic
    name: Restart

text_sensor:
# to find the ble mac address set debug level VERBOSE
#  - platform: ble_scanner
#    name: "BLE Devices Scanner"

  - platform: wifi_info
    ip_address:
      name: IP Address
      disabled_by_default: true
      entity_category: diagnostic

time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: Europe/Brussels
